//
// Generated by AlamofireRouterGenerator https://github.com/Mol0ko/AlamofireRouterGenerator.git
//


import Alamofire

enum NetworkRouter: URLRequestConvertible {
    
    //Advert
    case GETadvertidlong
    case POSTadvertidlongcomplaint(parameters: [String: Any])
    case POSTadvertidlongview
    //Chat
    case GETchatdialogs(parameters: [String: Any])
    case GETchatdialogidlongmessages(parameters: [String: Any])
    case POSTchatdialogidlongmessage(parameters: [String: Any])
    //Company
    case GETcompanyidlongadverts(parameters: [String: Any])
    case GETcompanyidlong
    //Favorite
    case GETfavoritecompanies(parameters: [String: Any])
    case POSTfavoritecompanyidlong
    case DELETEfavoritecompanyidlong
    case GETfavoriteadverts(parameters: [String: Any])
    case POSTfavoriteadvertidlong
    case DELETEfavoriteadvertidlong
    //Interesting
    case GETinterestingcategories(parameters: [String: Any])
    case GETinterestingcategoryidlongsubcategories(parameters: [String: Any])
    case GETinterestingsubcategoryidlongadverts(parameters: [String: Any])
    case GETinterestingcategoryidlongsubcategorieslist
    //Life
    case GETlifesituations
    case GETlifesituationidlongadverts(parameters: [String: Any])
    //Login
    case POSTlogin(parameters: [String: Any])
    //Plans
    case DELETEplansidlong
    case POSTplans(parameters: [String: Any])
    case PUTplansidlong(parameters: [String: Any])
    case GETplans(parameters: [String: Any])
    case GETplanshistory(parameters: [String: Any])
    //Product
    case POSTproductidlongdiscount
    //Profile
    case DELETEprofile
    case GETprofilechecks
    case GETprofilecategories
    case GETprofilecategoryidlongsubcategories
    case PUTprofilecategoriesorder(parameters: [String: Any])
    case POSTprofilecategoryidlongsubcategories(parameters: [String: Any])
    case GETprofileinfo
    case PUTprofileinfo(parameters: [String: Any])
    case GETprofileinspiration
    case PUTprofileinspiration(parameters: [String: Any])
    //Register
    case POSTregister(parameters: [String: Any])
    //Search
    case GETsearchformats
    case GETsearchnames
    case GETsearch
    //Settings
    case PUTsettingspassword(parameters: [String: Any])
    case POSTsettingstoken(parameters: [String: Any])
    case DELETEsettingstoken(parameters: [String: Any])
    //Top
    case GETtop(parameters: [String: Any])
    
    
    var method: HTTPMethod {
        switch self {
        case
        .GETadvertidlong,
        .GETchatdialogs,
        .GETchatdialogidlongmessages,
        .GETcompanyidlongadverts,
        .GETcompanyidlong,
        .GETfavoritecompanies,
        .GETfavoriteadverts,
        .GETinterestingcategories,
        .GETinterestingcategoryidlongsubcategories,
        .GETinterestingsubcategoryidlongadverts,
        .GETinterestingcategoryidlongsubcategorieslist,
        .GETlifesituations,
        .GETlifesituationidlongadverts,
        .GETplans,
        .GETplanshistory,
        .GETprofilechecks,
        .GETprofilecategories,
        .GETprofilecategoryidlongsubcategories,
        .GETprofileinfo,
        .GETprofileinspiration,
        .GETsearchformats,
        .GETsearchnames,
        .GETsearch,
        .GETtop:
            return .get
        case
        .POSTadvertidlongcomplaint,
        .POSTadvertidlongview,
        .POSTchatdialogidlongmessage,
        .POSTfavoritecompanyidlong,
        .POSTfavoriteadvertidlong,
        .POSTlogin,
        .POSTplans,
        .POSTproductidlongdiscount,
        .POSTprofilecategoryidlongsubcategories,
        .POSTregister,
        .POSTsettingstoken:
            return .post
        case
        .PUTplansidlong,
        .PUTprofilecategoriesorder,
        .PUTprofileinfo,
        .PUTprofileinspiration,
        .PUTsettingspassword:
            return .put
        case
        .DELETEfavoritecompanyidlong,
        .DELETEfavoriteadvertidlong,
        .DELETEplansidlong,
        .DELETEprofile,
        .DELETEsettingstoken:
            return .delete
        }
    }
    
    var baseURL: String {
        return "http://u0354994.plsk.regruhosting.ru/api/"
    }
    
    var path: String {
        switch self {
        case .GETadvertidlong:
            return "advert/1"
        case .POSTadvertidlongcomplaint:
            return "advert/1/complaint"
        case .POSTadvertidlongview:
            return "advert/1/view"
        case .GETchatdialogs:
            return "chat/dialogs"
        case .GETchatdialogidlongmessages:
            return "chat/dialog/3/messages"
        case .POSTchatdialogidlongmessage:
            return "chat/dialog/3/message"
        case .GETcompanyidlongadverts:
            return "company/3/adverts"
        case .GETcompanyidlong:
            return "company/3"
        case .GETfavoritecompanies:
            return "favorite/companies"
        case .POSTfavoritecompanyidlong:
            return "favorite/company/11"
        case .DELETEfavoritecompanyidlong:
            return "favorite/company/11"
        case .GETfavoriteadverts:
            return "favorite/adverts"
        case .POSTfavoriteadvertidlong:
            return "favorite/advert/1"
        case .DELETEfavoriteadvertidlong:
            return "favorite/advert/1"
        case .GETinterestingcategories:
            return "interesting/categories"
        case .GETinterestingcategoryidlongsubcategories:
            return "interesting/category/1/subcategories"
        case .GETinterestingsubcategoryidlongadverts:
            return "interesting/subcategory/1/adverts"
        case .GETinterestingcategoryidlongsubcategorieslist:
            return "interesting/category/1/subcategories/list"
        case .GETlifesituations:
            return "life/situations"
        case .GETlifesituationidlongadverts:
            return "life/situation/1/adverts"
        case .POSTlogin:
            return "login"
        case .DELETEplansidlong:
            return "plans/1"
        case .POSTplans:
            return "plans"
        case .PUTplansidlong:
            return "plans/2"
        case .GETplans:
            return "plans"
        case .GETplanshistory:
            return "plans/history"
        case .POSTproductidlongdiscount:
            return "product/4/discount"
        case .DELETEprofile:
            return "profile"
        case .GETprofilechecks:
            return "profile/checks"
        case .GETprofilecategories:
            return "profile/categories"
        case .GETprofilecategoryidlongsubcategories:
            return "profile/category/1/subcategories"
        case .PUTprofilecategoriesorder:
            return "profile/categories/order"
        case .POSTprofilecategoryidlongsubcategories:
            return "profile/category/1/subcategories"
        case .GETprofileinfo:
            return "profile/info"
        case .PUTprofileinfo:
            return "profile/info"
        case .GETprofileinspiration:
            return "profile/inspiration"
        case .PUTprofileinspiration:
            return "profile/inspiration"
        case .POSTregister:
            return "register"
        case .GETsearchformats:
            return "search/formats"
        case .GETsearchnames:
            return ""
        case .GETsearch:
            return ""
        case .PUTsettingspassword:
            return "settings/password"
        case .POSTsettingstoken:
            return "settings/token"
        case .DELETEsettingstoken:
            return "settings/token"
        case .GETtop:
            return "top"
        }
    }
    
    //MARK: - URLRequestConvertible
    //MARK: -
    
    func asURLRequest() throws -> URLRequest {
        let url = try baseURL.asURL()
        var urlRequest = URLRequest(url: url.appendingPathComponent(path))
        urlRequest.httpMethod = method.rawValue
        urlRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")
        
        switch self {
        //set parameters for requests with parameters:
        case
        .POSTadvertidlongcomplaint(let parameters),
        .GETchatdialogs(let parameters),
        .GETchatdialogidlongmessages(let parameters),
        .POSTchatdialogidlongmessage(let parameters),
        .GETcompanyidlongadverts(let parameters),
        .GETfavoritecompanies(let parameters),
        .GETfavoriteadverts(let parameters),
        .GETinterestingcategories(let parameters),
        .GETinterestingcategoryidlongsubcategories(let parameters),
        .GETinterestingsubcategoryidlongadverts(let parameters),
        .GETlifesituationidlongadverts(let parameters),
        .POSTlogin(let parameters),
        .POSTplans(let parameters),
        .PUTplansidlong(let parameters),
        .GETplans(let parameters),
        .GETplanshistory(let parameters),
        .PUTprofilecategoriesorder(let parameters),
        .POSTprofilecategoryidlongsubcategories(let parameters),
        .PUTprofileinfo(let parameters),
        .PUTprofileinspiration(let parameters),
        .POSTregister(let parameters),
        .PUTsettingspassword(let parameters),
        .POSTsettingstoken(let parameters),
        .DELETEsettingstoken(let parameters),
        .GETtop(let parameters):
            urlRequest.httpBody = try JSONSerialization.data(withJSONObject: parameters)
            break
        default:
            break
        }
        return urlRequest
    }
}
